# Generated by Django 4.2.5 on 2023-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='jumlah',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='product',
            name='nilai',
            field=models.CharField(max_length=2),
        ),
    ]
