# Generated by Django 4.2.5 on 2023-09-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_jumlah_product_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='deskripsi',
        ),
    ]
