# Generated by Django 4.2.5 on 2023-09-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_product_deskripsi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='classes',
            new_name='kelas',
        ),
    ]
